"""Background music and sound effects the AI may use: only files listed with a free licence.

``assets/music/licenses.json`` and ``assets/sfx/licenses.json`` list each file::

    {"file": "calm.m4a", "mood": "calm", "license": "CC0-1.0", "source": "...", "bpm": 60}

The starter library is generated by ``scripts/make_audio_library.py``: original to this project, so it
carries no third-party rights (a CC0 track from a popular site can still be claimed by YouTube's Content
ID when someone else registered it). The owner may add stock tracks the same way; only licences in
FREE_AUDIO_LICENSES are offered, and a listed file that is missing is ignored.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ASSETS = Path(__file__).resolve().parents[4] / "assets"
FREE_AUDIO_LICENSES = {"CC0-1.0", "Pixabay Content License", "Public Domain"}


def _load(folder: Path) -> list[dict[str, Any]]:
    manifest = folder / "licenses.json"
    if not manifest.exists():
        return []
    out = []
    for entry in json.loads(manifest.read_text(encoding="utf-8")):
        path = folder / str(entry.get("file", ""))
        if entry.get("license") in FREE_AUDIO_LICENSES and path.is_file():
            out.append({**entry, "path": path})
    return out


def music_tracks(folder: Path | None = None) -> list[dict[str, Any]]:
    return _load(folder or ASSETS / "music")


def music_moods(folder: Path | None = None) -> list[str]:
    return sorted({str(t["mood"]) for t in music_tracks(folder)})


def track_for(mood: str, folder: Path | None = None) -> Path | None:
    for t in music_tracks(folder):
        if t["mood"] == mood:
            return Path(t["path"])
    return None


def sfx(name: str, folder: Path | None = None) -> Path | None:
    for t in _load(folder or ASSETS / "sfx"):
        if t.get("name") == name:
            return Path(t["path"])
    return None
