"""`aimz schedule`: register the autonomous cycle with Windows Task Scheduler (cron hint elsewhere)."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

TASK_PREFIX = "AI Media Zero"


def runner_script(project_root: Path) -> Path:
    """Write scripts/run-cycle.ps1 that activates the venv and runs one cycle, logging to data/logs."""
    scripts = project_root / "scripts"
    scripts.mkdir(exist_ok=True)
    path = scripts / "run-cycle.ps1"
    exe = project_root / ".venv" / "Scripts" / "aimz.exe"
    path.write_text(
        "# Generated by `aimz schedule install`. Runs one autonomous cycle and appends to data/logs/scheduled.log\n"
        f"Set-Location '{project_root}'\n"
        f"& '{exe}' run *>> '{project_root / 'data' / 'logs' / 'scheduled.log'}'\n",
        encoding="utf-8",
    )
    return path


def task_name(hhmm: str) -> str:
    return f"{TASK_PREFIX} {hhmm.replace(':', '')}"


def install(project_root: Path, times: list[str]) -> list[str]:
    if os.name != "nt":
        raise RuntimeError("Task Scheduler is Windows-only; use cron: " + cron_line(project_root, times))
    script = runner_script(project_root)
    created: list[str] = []
    for t in times:
        name = task_name(t)
        cmd = [
            "schtasks",
            "/Create",
            "/F",
            "/TN",
            name,
            "/SC",
            "DAILY",
            "/ST",
            t,
            "/TR",
            f'powershell.exe -NoProfile -ExecutionPolicy Bypass -File "{script}"',
        ]
        proc = subprocess.run(cmd, capture_output=True, text=True)
        if proc.returncode != 0:
            raise RuntimeError(f"schtasks failed for {name}: {proc.stderr or proc.stdout}")
        created.append(name)
    return created


def remove(times: list[str] | None = None) -> list[str]:
    if os.name != "nt":
        return []
    removed: list[str] = []
    names = [task_name(t) for t in times] if times else [ln for ln in list_tasks()]
    for name in names:
        proc = subprocess.run(["schtasks", "/Delete", "/F", "/TN", name], capture_output=True, text=True)
        if proc.returncode == 0:
            removed.append(name)
    return removed


def list_tasks() -> list[str]:
    if os.name != "nt":
        return []
    proc = subprocess.run(["schtasks", "/Query", "/FO", "CSV", "/NH"], capture_output=True, text=True)
    out: list[str] = []
    for line in proc.stdout.splitlines():
        if TASK_PREFIX in line:
            name = line.split('","')[0].strip('"').lstrip("\\")
            out.append(name)
    return out


def cron_line(project_root: Path, times: list[str]) -> str:
    exe = project_root / ".venv" / "bin" / "aimz"
    lines = []
    for t in times:
        hh, mm = t.split(":")
        lines.append(
            f"{int(mm)} {int(hh)} * * * cd {project_root} && {exe} run >> {project_root}/data/logs/scheduled.log 2>&1"
        )
    return "\n".join(lines)


def python_exe() -> str:
    return sys.executable
