"""`aimz schedule`: register the autonomous cycle with Windows Task Scheduler (cron hint elsewhere)."""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from datetime import date
from pathlib import Path
from xml.sax.saxutils import escape

TASK_PREFIX = "AI Media Zero"
_DOMAIN_SEP = chr(92)  # backslash, kept out of f-strings

# Windows Smart App Control refuses to start the unsigned console-script shim
# that pip drops in .venv\Scripts. PowerShell does not fold a native launch
# failure into its own exit code, so the task recorded success while nothing
# ran. Both problems are handled here: launch via the interpreter, and treat an
# unset $LASTEXITCODE as a failure.
_RUNNER = """# Generated by `aimz schedule install`. Runs one autonomous cycle.
# Launched through the interpreter rather than the venv aimz.exe shim: Smart App
# Control blocks that unsigned shim, and PowerShell reports success regardless.
$root = '{root}'
$py   = '{python}'
$log  = '{log}'

Set-Location $root

"=== cycle start $(Get-Date -Format o) ===" | Out-File -FilePath $log -Append -Encoding utf8

if (-not (Test-Path -LiteralPath $py)) {{
    "FATAL: interpreter not found at $py" | Out-File -FilePath $log -Append -Encoding utf8
    exit 1
}}

$env:PYTHONUTF8 = '1'
$env:PYTHONIOENCODING = 'utf-8'

# cmd.exe performs the redirect at the OS level. PowerShell 5.1's own `*>>`
# wraps every stderr line in a NativeCommandError record and writes the file as
# UTF-16, which leaves the log unreadable next to the UTF-8 markers above.
# Clear the exit code first, so a process that never started is distinguishable
# from one that started and returned 0.
$global:LASTEXITCODE = $null
& cmd.exe /c "`"$py`" -m aimz run >> `"$log`" 2>&1"
$code = $LASTEXITCODE
if ($null -eq $code) {{
    "FATAL: '$py' did not start; blocked by policy or missing" | Out-File -FilePath $log -Append -Encoding utf8
    $code = 1
}}

"=== cycle end $(Get-Date -Format o) exit=$code ===" | Out-File -FilePath $log -Append -Encoding utf8
exit $code
"""


def runner_script(project_root: Path) -> Path:
    """Write scripts/run-cycle.ps1 that runs one cycle, logging to data/logs/scheduled.log."""
    scripts = project_root / "scripts"
    scripts.mkdir(exist_ok=True)
    path = scripts / "run-cycle.ps1"
    path.write_text(
        _RUNNER.format(
            root=project_root,
            python=venv_python(project_root),
            log=project_root / "data" / "logs" / "scheduled.log",
        ),
        encoding="utf-8",
    )
    return path


def venv_python(project_root: Path) -> Path:
    """The interpreter the scheduled task should use, preferring the project venv."""
    candidate = project_root / ".venv" / ("Scripts" if os.name == "nt" else "bin")
    candidate = candidate / ("python.exe" if os.name == "nt" else "python")
    return candidate if candidate.exists() else Path(sys.executable)


def task_name(hhmm: str) -> str:
    return f"{TASK_PREFIX} {hhmm.replace(':', '')}"


def _task_xml(hhmm: str, script: Path, project_root: Path) -> str:
    """Task Scheduler XML for one daily run.

    schtasks /Create cannot express the settings that matter here, so the task
    is registered from XML instead. The defaults it would otherwise inherit
    refuse to start on battery and silently drop any run the machine sleeps
    through, which is fatal for an unattended channel on a laptop.
    """
    user = os.environ.get("USERNAME", "")
    domain = os.environ.get("USERDOMAIN", "")
    user_id = f"{domain}{_DOMAIN_SEP}{user}" if domain and user else user
    args = f'-NoProfile -ExecutionPolicy Bypass -File "{script}"'
    return f"""<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>AI Media Zero: one autonomous cycle at {escape(hhmm)}.</Description>
  </RegistrationInfo>
  <Triggers>
    <CalendarTrigger>
      <StartBoundary>{date.today().isoformat()}T{escape(hhmm)}:00</StartBoundary>
      <Enabled>true</Enabled>
      <ScheduleByDay><DaysInterval>1</DaysInterval></ScheduleByDay>
    </CalendarTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>{escape(user_id)}</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>true</WakeToRun>
    <ExecutionTimeLimit>PT4H</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>powershell.exe</Command>
      <Arguments>{escape(args)}</Arguments>
      <WorkingDirectory>{escape(str(project_root))}</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
"""


def install(project_root: Path, times: list[str]) -> list[str]:
    if os.name != "nt":
        raise RuntimeError("Task Scheduler is Windows-only; use cron: " + cron_line(project_root, times))
    script = runner_script(project_root)
    created: list[str] = []
    for t in times:
        name = task_name(t)
        xml = _task_xml(t, script, project_root)
        # schtasks only reads task XML as UTF-16.
        with tempfile.NamedTemporaryFile(
            "w", suffix=".xml", encoding="utf-16", delete=False, newline="\r\n"
        ) as fh:
            fh.write(xml)
            xml_path = fh.name
        try:
            proc = subprocess.run(
                ["schtasks", "/Create", "/F", "/TN", name, "/XML", xml_path],
                capture_output=True,
                text=True,
            )
        finally:
            os.unlink(xml_path)
        if proc.returncode != 0:
            raise RuntimeError(f"schtasks failed for {name}: {proc.stderr or proc.stdout}")
        created.append(name)
    return created


def remove(times: list[str] | None = None) -> list[str]:
    if os.name != "nt":
        return []
    removed: list[str] = []
    names = [task_name(t) for t in times] if times else [ln for ln in list_tasks()]
    for name in names:
        proc = subprocess.run(["schtasks", "/Delete", "/F", "/TN", name], capture_output=True, text=True)
        if proc.returncode == 0:
            removed.append(name)
    return removed


def list_tasks() -> list[str]:
    if os.name != "nt":
        return []
    proc = subprocess.run(["schtasks", "/Query", "/FO", "CSV", "/NH"], capture_output=True, text=True)
    out: list[str] = []
    for line in proc.stdout.splitlines():
        if TASK_PREFIX in line:
            name = line.split('","')[0].strip('"').lstrip("\\")
            out.append(name)
    return out


def cron_line(project_root: Path, times: list[str]) -> str:
    py = venv_python(project_root)
    lines = []
    for t in times:
        hh, mm = t.split(":")
        lines.append(
            f"{int(mm)} {int(hh)} * * * cd {project_root} && {py} -m aimz run "
            f">> {project_root}/data/logs/scheduled.log 2>&1"
        )
    return "\n".join(lines)


def python_exe() -> str:
    return sys.executable
