"""`aimz schedule`: register the autonomous cycle with Windows Task Scheduler (cron hint elsewhere)."""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from datetime import date
from pathlib import Path
from xml.sax.saxutils import escape

TASK_PREFIX = "AI Media Zero"
MAIN = "main"  # the original channel, at the repository root
_DOMAIN_SEP = chr(92)  # backslash, kept out of f-strings

# Windows Smart App Control refuses to start the unsigned console-script shim
# that pip drops in .venv\Scripts. PowerShell does not fold a native launch
# failure into its own exit code, so the task recorded success while nothing
# ran. Both problems are handled here: launch via the interpreter, and treat an
# unset $LASTEXITCODE as a failure.
_RUNNER = """# Generated by `aimz schedule install`. Runs one autonomous cycle.
# Launched through the interpreter rather than the venv aimz.exe shim: Smart App
# Control blocks that unsigned shim, and PowerShell reports success regardless.
$root = '{root}'
$py   = '{python}'
$log  = '{log}'
$skipLog = '{skip_log}'

Set-Location $root

# One cycle at a time. Two copies used to start together when the laptop woke after both scheduled
# times had passed; the second died writing to the log the first held open, with no line to show for it.
# The mutex is taken before the log is touched; a second copy notes itself in a separate file and exits.
# Windows releases the mutex if this process dies, so a crash never blocks the next cycle.
$mutex = New-Object System.Threading.Mutex($false, '{mutex}')
$owned = $false
try {{ $owned = $mutex.WaitOne(0) }} catch [System.Threading.AbandonedMutexException] {{ $owned = $true }}
if (-not $owned) {{
    try {{ "$(Get-Date -Format o) skipped: another cycle is already running" | Out-File -FilePath $skipLog -Append -Encoding utf8 }} catch {{ }}
    exit 0
}}

# Channels share one GPU and one Ollama, so their cycles run one at a time. Unlike a second copy of the
# same channel (skipped above), another channel's cycle is waited for, up to 2 hours.
$gpu = New-Object System.Threading.Mutex($false, 'Local\\AIMediaZeroGPU')
$gpuOwned = $false
try {{ $gpuOwned = $gpu.WaitOne([TimeSpan]::FromHours(2)) }} catch [System.Threading.AbandonedMutexException] {{ $gpuOwned = $true }}
if (-not $gpuOwned) {{
    try {{ "$(Get-Date -Format o) skipped: another channel's cycle held the GPU for 2 hours" | Out-File -FilePath $skipLog -Append -Encoding utf8 }} catch {{ }}
    $mutex.ReleaseMutex()
    exit 0
}}

"=== cycle start $(Get-Date -Format o) ===" | Out-File -FilePath $log -Append -Encoding utf8

if (-not (Test-Path -LiteralPath $py)) {{
    "FATAL: interpreter not found at $py" | Out-File -FilePath $log -Append -Encoding utf8
    exit 1
}}

$env:PYTHONUTF8 = '1'
$env:PYTHONIOENCODING = 'utf-8'

# Ollama has to be serving before the cycle starts. Scheduled runs failed with
# "model unreachable" whenever the Ollama app was not open, so start it here
# and wait until its HTTP API answers. (Owner decision D-012/D-015, 2026-09-13.)
$ollamaUrl = 'http://127.0.0.1:11434/api/tags'
function Test-Ollama {{
    try {{ Invoke-WebRequest -UseBasicParsing -Uri $ollamaUrl -TimeoutSec 3 | Out-Null; return $true }}
    catch {{ return $false }}
}}
if (-not (Test-Ollama)) {{
    "ollama not serving; starting it $(Get-Date -Format o)" | Out-File -FilePath $log -Append -Encoding utf8
    $ollama = Get-Command ollama -ErrorAction SilentlyContinue
    if ($null -eq $ollama) {{
        "FATAL: ollama is not on PATH; install Ollama or add it to PATH" | Out-File -FilePath $log -Append -Encoding utf8
        exit 1
    }}
    Start-Process -FilePath $ollama.Source -ArgumentList 'serve' -WindowStyle Hidden
    $ready = $false
    for ($i = 0; $i -lt 30; $i++) {{
        Start-Sleep -Seconds 2
        if (Test-Ollama) {{ $ready = $true; break }}
    }}
    if (-not $ready) {{
        "FATAL: ollama did not answer at $ollamaUrl within 60 s" | Out-File -FilePath $log -Append -Encoding utf8
        exit 1
    }}
    "ollama serving $(Get-Date -Format o)" | Out-File -FilePath $log -Append -Encoding utf8
}}

# cmd.exe performs the redirect at the OS level. PowerShell 5.1's own `*>>`
# wraps every stderr line in a NativeCommandError record and writes the file as
# UTF-16, which leaves the log unreadable next to the UTF-8 markers above.
# Clear the exit code first, so a process that never started is distinguishable
# from one that started and returned 0.
$global:LASTEXITCODE = $null
& cmd.exe /c "`"$py`" -m aimz {instance_args}run >> `"$log`" 2>&1"
$code = $LASTEXITCODE
if ($null -eq $code) {{
    "FATAL: '$py' did not start; blocked by policy or missing" | Out-File -FilePath $log -Append -Encoding utf8
    $code = 1
}}

"=== cycle end $(Get-Date -Format o) exit=$code ===" | Out-File -FilePath $log -Append -Encoding utf8

# A cycle that fails, or finishes degraded (exit 2: e.g. an expired platform token),
# raises a Windows notification. Unattended failures otherwise go unseen for days.
if ($code -ne 0) {{
    try {{
        $msg = if ($code -eq 2) {{ 'Cycle finished with errors. Run: python -m aimz status' }} else {{ "Cycle failed (exit $code). See data\\logs\\scheduled.log" }}
        [Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] | Out-Null
        $xml = [Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent([Windows.UI.Notifications.ToastTemplateType]::ToastText02)
        $text = $xml.GetElementsByTagName('text')
        $text.Item(0).AppendChild($xml.CreateTextNode('{title}')) | Out-Null
        $text.Item(1).AppendChild($xml.CreateTextNode($msg)) | Out-Null
        $appId = '{{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}}\\WindowsPowerShell\\v1.0\\powershell.exe'
        [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier($appId).Show([Windows.UI.Notifications.ToastNotification]::new($xml))
    }} catch {{
        "notification failed: $_" | Out-File -FilePath $log -Append -Encoding utf8
    }}
}}
$gpu.ReleaseMutex()
$mutex.ReleaseMutex()
exit $code
"""


def runner_script(project_root: Path, instance: str = MAIN, instance_root: Path | None = None) -> Path:
    """Write the runner for one instance: ``scripts/run-cycle.ps1`` for main, ``<instance>/run-cycle.ps1``
    otherwise. It runs from the repository (code, venv) and logs to the instance's ``data/logs``."""
    home = instance_root or project_root
    if instance == MAIN:
        folder = project_root / "scripts"
        folder.mkdir(exist_ok=True)
    else:
        folder = home
    path = folder / "run-cycle.ps1"
    path.write_text(
        _RUNNER.format(
            root=project_root,
            python=venv_python(project_root),
            log=home / "data" / "logs" / "scheduled.log",
            skip_log=home / "data" / "logs" / "scheduled-skipped.log",
            mutex="Local\\AIMediaZeroCycle" if instance == MAIN else f"Local\\AIMediaZeroCycle-{instance}",
            instance_args="" if instance == MAIN else f"--instance {instance} ",
            title="AI Media Zero" if instance == MAIN else f"AI Media Zero ({instance})",
        ),
        encoding="utf-8",
    )
    return path


def venv_python(project_root: Path) -> Path:
    """The interpreter the scheduled task should use, preferring the project venv."""
    candidate = project_root / ".venv" / ("Scripts" if os.name == "nt" else "bin")
    candidate = candidate / ("python.exe" if os.name == "nt" else "python")
    return candidate if candidate.exists() else Path(sys.executable)


def task_name(hhmm: str | None = None, instance: str = MAIN) -> str:
    """The task's name: "AI Media Zero" for the main channel, "AI Media Zero - <name>" for another instance.
    ``hhmm`` names the main channel's old one-task-per-time layout, kept for removal."""
    if instance != MAIN:
        return f"{TASK_PREFIX} - {instance}"
    return f"{TASK_PREFIX} {hhmm.replace(':', '')}" if hhmm else TASK_PREFIX


def instance_of(task: str) -> str:
    """Which instance a task belongs to (the old per-time tasks belong to main)."""
    return task[len(TASK_PREFIX) + 3 :] if task.startswith(f"{TASK_PREFIX} - ") else MAIN


def _task_xml(times: list[str], script: Path, project_root: Path) -> str:
    """Task Scheduler XML: one task, one daily trigger per time.

    One task rather than one per time: Task Scheduler's IgnoreNew policy only stops a task overlapping
    *itself*, so two tasks both caught up at wake and ran together. Within one task a second trigger that
    fires while a cycle is running is simply skipped.

    schtasks /Create cannot express the settings that matter here, so the task
    is registered from XML instead. The defaults it would otherwise inherit
    refuse to start on battery and silently drop any run the machine sleeps
    through, which is fatal for an unattended channel on a laptop.
    """
    user = os.environ.get("USERNAME", "")
    domain = os.environ.get("USERDOMAIN", "")
    user_id = f"{domain}{_DOMAIN_SEP}{user}" if domain and user else user
    args = f'-NoProfile -ExecutionPolicy Bypass -File "{script}"'
    triggers = "".join(
        f"""
    <CalendarTrigger>
      <StartBoundary>{date.today().isoformat()}T{escape(hhmm)}:00</StartBoundary>
      <Enabled>true</Enabled>
      <ScheduleByDay><DaysInterval>1</DaysInterval></ScheduleByDay>
    </CalendarTrigger>"""
        for hhmm in times
    )
    return f"""<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>AI Media Zero: one autonomous cycle daily at {escape(", ".join(times))}.</Description>
  </RegistrationInfo>
  <Triggers>{triggers}
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>{escape(user_id)}</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>true</WakeToRun>
    <ExecutionTimeLimit>PT4H</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>powershell.exe</Command>
      <Arguments>{escape(args)}</Arguments>
      <WorkingDirectory>{escape(str(project_root))}</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
"""


def install(
    project_root: Path, times: list[str], instance: str = MAIN, instance_root: Path | None = None
) -> tuple[str, list[str]]:
    """Register this instance's task, then delete this instance's other tasks (main's old per-time ones).
    Other channels' tasks are never touched.

    The new task is created first and confirmed to exist before anything is removed, so a failure never
    leaves the channel with no schedule. Returns (task name, removed task names).
    """
    if os.name != "nt":
        raise RuntimeError("Task Scheduler is Windows-only; use cron: " + cron_line(project_root, times))
    if not times:
        raise RuntimeError("no times given")
    script = runner_script(project_root, instance, instance_root)
    name = task_name(instance=instance)
    xml = _task_xml(times, script, project_root)
    # schtasks only reads task XML as UTF-16.
    with tempfile.NamedTemporaryFile(
        "w", suffix=".xml", encoding="utf-16", delete=False, newline="\r\n"
    ) as fh:
        fh.write(xml)
        xml_path = fh.name
    try:
        proc = subprocess.run(
            ["schtasks", "/Create", "/F", "/TN", name, "/XML", xml_path],
            capture_output=True,
            text=True,
        )
    finally:
        os.unlink(xml_path)
    if proc.returncode != 0:
        raise RuntimeError(f"schtasks failed for {name}: {proc.stderr or proc.stdout}")
    if name not in list_tasks():
        raise RuntimeError(f"{name} was not found after creating it; old tasks left in place")
    mine = [t for t in list_tasks() if t != name and instance_of(t) == instance]
    removed = remove(mine)
    leftover = [t for t in list_tasks() if t != name and instance_of(t) == instance]
    if leftover:
        raise RuntimeError(f"{name} installed, but these old tasks could not be removed: {leftover}")
    return name, removed


def remove(names: list[str] | None = None, instance: str | None = None) -> list[str]:
    """Delete the named tasks, or every task of ``instance`` (every AI Media Zero task when both are None)."""
    if os.name != "nt":
        return []
    removed: list[str] = []
    if names is None:
        names = [t for t in list_tasks() if instance is None or instance_of(t) == instance]
    for name in names:
        proc = subprocess.run(["schtasks", "/Delete", "/F", "/TN", name], capture_output=True, text=True)
        if proc.returncode == 0:
            removed.append(name)
    return removed


def list_tasks() -> list[str]:
    if os.name != "nt":
        return []
    proc = subprocess.run(["schtasks", "/Query", "/FO", "CSV", "/NH"], capture_output=True, text=True)
    out: list[str] = []
    for line in proc.stdout.splitlines():
        if TASK_PREFIX in line:
            name = line.split('","')[0].strip('"').lstrip("\\")
            if name not in out:
                out.append(name)
    return out


def cron_line(project_root: Path, times: list[str]) -> str:
    py = venv_python(project_root)
    lines = []
    for t in times:
        hh, mm = t.split(":")
        lines.append(
            f"{int(mm)} {int(hh)} * * * cd {project_root} && {py} -m aimz run "
            f">> {project_root}/data/logs/scheduled.log 2>&1"
        )
    return "\n".join(lines)


def python_exe() -> str:
    return sys.executable
