"""Generate the starter music and sound-effect library (original, CC0). Deterministic: same files every run.

    .venv\\Scripts\\python.exe scripts\\make_audio_library.py

Writes assets/music/{calm,tense,bright}.m4a (32 s seamless loops) and assets/sfx/whoosh.m4a, plus each
folder's licenses.json. Everything is synthesised here from sine waves and filtered noise, so the files are
original to this project and carry no third-party rights.
"""

from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import wave
from pathlib import Path

import numpy as np

RATE = 44100
ROOT = Path(__file__).resolve().parents[1]
LICENSE = "CC0-1.0"
SOURCE = "generated by scripts/make_audio_library.py (original to AI Media Zero)"


def note(midi: float) -> float:
    return float(440.0 * 2 ** ((midi - 69) / 12))


def pad(freqs: list[float], seconds: float) -> np.ndarray:
    """A soft chord: sines with a little second harmonic and slow vibrato, faded in and out."""
    t = np.arange(int(seconds * RATE)) / RATE
    out = np.zeros_like(t)
    for f in freqs:
        vib = 1 + 0.002 * np.sin(2 * np.pi * 0.3 * t)
        out += np.sin(2 * np.pi * f * vib * t) + 0.25 * np.sin(2 * np.pi * 2 * f * t)
    env = np.minimum(1.0, np.minimum(t / 0.8, (seconds - t) / 0.8))
    return out * env / len(freqs)


def pluck(freq: float, seconds: float) -> np.ndarray:
    t = np.arange(int(seconds * RATE)) / RATE
    return (np.sin(2 * np.pi * freq * t) + 0.3 * np.sin(2 * np.pi * 3 * freq * t)) * np.exp(-t * 6)


def progression(chords: list[list[int]], chord_s: float) -> np.ndarray:
    return np.concatenate([pad([note(m) for m in c], chord_s) for c in chords])


def calm() -> np.ndarray:
    # Cmaj7 - Am7 - Fmaj7 - G6, 4 s each, played twice: a 32 s loop.
    chords = [[48, 52, 55, 59], [45, 52, 55, 60], [41, 48, 52, 57], [43, 50, 55, 59]]
    return np.tile(progression(chords, 4.0), 2) * 0.6


def tense() -> np.ndarray:
    # A low drone under Am - F - Dm - E, with a slow tremolo pulse.
    body = np.tile(progression([[45, 48, 52], [41, 45, 48], [38, 45, 50], [40, 44, 47]], 4.0), 2)
    t = np.arange(len(body)) / RATE
    drone = 0.5 * np.sin(2 * np.pi * note(33) * t)
    trem = 0.75 + 0.25 * np.sin(2 * np.pi * 2.0 * t)
    return (body + drone) * trem * 0.5


def bright() -> np.ndarray:
    # Major pad with eighth-note arpeggio plucks at 120 bpm.
    chords = [[48, 52, 55], [43, 47, 50], [45, 48, 52], [41, 45, 48]]
    bed = np.tile(progression(chords, 4.0), 2) * 0.45
    step = int(0.25 * RATE)
    for i in range(len(bed) // step):
        chord = chords[(i * step // int(4.0 * RATE)) % 4]
        f = note(chord[i % 3] + 12)
        p = pluck(f, 0.5)
        end = min(len(bed), i * step + len(p))
        bed[i * step : end] += 0.35 * p[: end - i * step]
    return bed


def whoosh() -> np.ndarray:
    """0.4 s of noise swept through a moving low-pass filter, rising then falling."""
    rng = np.random.default_rng(7)
    n = int(0.4 * RATE)
    noise = rng.standard_normal(n)
    t = np.linspace(0, 1, n)
    cutoff = 300 + 5000 * np.sin(np.pi * t) ** 2
    out = np.zeros(n)
    y = 0.0
    for i in range(n):
        a = 1 - np.exp(-2 * np.pi * cutoff[i] / RATE)
        y += a * (noise[i] - y)
        out[i] = y
    return out * np.sin(np.pi * t) ** 1.5 * 0.9


def write(path: Path, samples: np.ndarray) -> None:
    samples = samples / max(1e-9, float(np.max(np.abs(samples)))) * 0.8
    pcm = (samples * 32767).astype("<i2").tobytes()
    with tempfile.TemporaryDirectory() as tmp:
        wav = Path(tmp) / "x.wav"
        with wave.open(str(wav), "wb") as w:
            w.setnchannels(1)
            w.setsampwidth(2)
            w.setframerate(RATE)
            w.writeframes(pcm)
        from aimz.providers.video.ffmpeg_renderer import resolve_ffmpeg

        ffmpeg = resolve_ffmpeg()
        if not ffmpeg:
            sys.exit("ffmpeg not found")
        subprocess.run(
            [
                ffmpeg,
                "-hide_banner",
                "-loglevel",
                "error",
                "-y",
                "-i",
                str(wav),
                "-c:a",
                "aac",
                "-b:a",
                "96k",
                str(path),
            ],
            check=True,
        )


def main() -> None:
    music = ROOT / "assets" / "music"
    sfx = ROOT / "assets" / "sfx"
    music.mkdir(parents=True, exist_ok=True)
    sfx.mkdir(parents=True, exist_ok=True)
    tracks = [("calm", calm(), 60), ("tense", tense(), 60), ("bright", bright(), 120)]
    entries = []
    for mood, samples, bpm in tracks:
        write(music / f"{mood}.m4a", samples)
        entries.append(
            {"file": f"{mood}.m4a", "mood": mood, "bpm": bpm, "license": LICENSE, "source": SOURCE}
        )
    (music / "licenses.json").write_text(json.dumps(entries, indent=2) + "\n", encoding="utf-8")
    write(sfx / "whoosh.m4a", whoosh())
    (sfx / "licenses.json").write_text(
        json.dumps([{"file": "whoosh.m4a", "name": "whoosh", "license": LICENSE, "source": SOURCE}], indent=2)
        + "\n",
        encoding="utf-8",
    )
    print(f"wrote {len(entries)} music tracks and 1 sound effect")


if __name__ == "__main__":
    main()
