# Generated by `aimz schedule install`. Runs one autonomous cycle.
# Launched through the interpreter rather than the venv aimz.exe shim: Smart App
# Control blocks that unsigned shim, and PowerShell reports success regardless.
$root = 'C:\Users\scott\Documents\Agentic_Youtube'
$py   = 'C:\Users\scott\Documents\Agentic_Youtube\.venv\Scripts\python.exe'
$log  = 'C:\Users\scott\Documents\Agentic_Youtube\data\logs\scheduled.log'

Set-Location $root

"=== cycle start $(Get-Date -Format o) ===" | Out-File -FilePath $log -Append -Encoding utf8

if (-not (Test-Path -LiteralPath $py)) {
    "FATAL: interpreter not found at $py" | Out-File -FilePath $log -Append -Encoding utf8
    exit 1
}

$env:PYTHONUTF8 = '1'
$env:PYTHONIOENCODING = 'utf-8'

# Ollama has to be serving before the cycle starts. Scheduled runs failed with
# "model unreachable" whenever the Ollama app was not open, so start it here
# and wait until its HTTP API answers. (Owner decision D-012/D-015, 2026-09-13.)
$ollamaUrl = 'http://127.0.0.1:11434/api/tags'
function Test-Ollama {
    try { Invoke-WebRequest -UseBasicParsing -Uri $ollamaUrl -TimeoutSec 3 | Out-Null; return $true }
    catch { return $false }
}
if (-not (Test-Ollama)) {
    "ollama not serving; starting it $(Get-Date -Format o)" | Out-File -FilePath $log -Append -Encoding utf8
    $ollama = Get-Command ollama -ErrorAction SilentlyContinue
    if ($null -eq $ollama) {
        "FATAL: ollama is not on PATH; install Ollama or add it to PATH" | Out-File -FilePath $log -Append -Encoding utf8
        exit 1
    }
    Start-Process -FilePath $ollama.Source -ArgumentList 'serve' -WindowStyle Hidden
    $ready = $false
    for ($i = 0; $i -lt 30; $i++) {
        Start-Sleep -Seconds 2
        if (Test-Ollama) { $ready = $true; break }
    }
    if (-not $ready) {
        "FATAL: ollama did not answer at $ollamaUrl within 60 s" | Out-File -FilePath $log -Append -Encoding utf8
        exit 1
    }
    "ollama serving $(Get-Date -Format o)" | Out-File -FilePath $log -Append -Encoding utf8
}

# cmd.exe performs the redirect at the OS level. PowerShell 5.1's own `*>>`
# wraps every stderr line in a NativeCommandError record and writes the file as
# UTF-16, which leaves the log unreadable next to the UTF-8 markers above.
# Clear the exit code first, so a process that never started is distinguishable
# from one that started and returned 0.
$global:LASTEXITCODE = $null
& cmd.exe /c "`"$py`" -m aimz run >> `"$log`" 2>&1"
$code = $LASTEXITCODE
if ($null -eq $code) {
    "FATAL: '$py' did not start; blocked by policy or missing" | Out-File -FilePath $log -Append -Encoding utf8
    $code = 1
}

"=== cycle end $(Get-Date -Format o) exit=$code ===" | Out-File -FilePath $log -Append -Encoding utf8

# A cycle that fails, or finishes degraded (exit 2: e.g. an expired platform token),
# raises a Windows notification. Unattended failures otherwise go unseen for days.
if ($code -ne 0) {
    try {
        $msg = if ($code -eq 2) { 'Cycle finished with errors. Run: python -m aimz status' } else { "Cycle failed (exit $code). See data\logs\scheduled.log" }
        [Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] | Out-Null
        $xml = [Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent([Windows.UI.Notifications.ToastTemplateType]::ToastText02)
        $text = $xml.GetElementsByTagName('text')
        $text.Item(0).AppendChild($xml.CreateTextNode('AI Media Zero')) | Out-Null
        $text.Item(1).AppendChild($xml.CreateTextNode($msg)) | Out-Null
        $appId = '{1AC14E77-02E7-4E5D-B744-2EB1AE5198B7}\WindowsPowerShell\v1.0\powershell.exe'
        [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier($appId).Show([Windows.UI.Notifications.ToastNotification]::new($xml))
    } catch {
        "notification failed: $_" | Out-File -FilePath $log -Append -Encoding utf8
    }
}
exit $code
