# Generated by `aimz schedule install`. Runs one autonomous cycle.
# Launched through the interpreter rather than the venv aimz.exe shim: Smart App
# Control blocks that unsigned shim, and PowerShell reports success regardless.
$root = 'C:\Users\scott\Documents\Agentic_Youtube'
$py   = 'C:\Users\scott\Documents\Agentic_Youtube\.venv\Scripts\python.exe'
$log  = 'C:\Users\scott\Documents\Agentic_Youtube\data\logs\scheduled.log'

Set-Location $root

"=== cycle start $(Get-Date -Format o) ===" | Out-File -FilePath $log -Append -Encoding utf8

if (-not (Test-Path -LiteralPath $py)) {
    "FATAL: interpreter not found at $py" | Out-File -FilePath $log -Append -Encoding utf8
    exit 1
}

$env:PYTHONUTF8 = '1'
$env:PYTHONIOENCODING = 'utf-8'

# cmd.exe performs the redirect at the OS level. PowerShell 5.1's own `*>>`
# wraps every stderr line in a NativeCommandError record and writes the file as
# UTF-16, which leaves the log unreadable next to the UTF-8 markers above.
# Clear the exit code first, so a process that never started is distinguishable
# from one that started and returned 0.
$global:LASTEXITCODE = $null
& cmd.exe /c "`"$py`" -m aimz run >> `"$log`" 2>&1"
$code = $LASTEXITCODE
if ($null -eq $code) {
    "FATAL: '$py' did not start; blocked by policy or missing" | Out-File -FilePath $log -Append -Encoding utf8
    $code = 1
}

"=== cycle end $(Get-Date -Format o) exit=$code ===" | Out-File -FilePath $log -Append -Encoding utf8
exit $code
